### PR TITLE
Homework1

### PR DESCRIPTION
**Pull request by Yttehs-HDX**

### CODE REVIEW

**Comment by Vincent-ice** [comment]
请同步最新的主库

**Comment by Cai1Hsu** [comment]
```bash
# 添加上游源
git remote add upstream git@github.com:Vincent-ice/5th-loongson-class-in-NEUQ

# 拉取上游
git fetch upstream
git merge upstream/homework1

# 解决冲突
mv week\ 1/作业提交/*.md ./作业提交/
git rm week\ 1/ -r

# 提交 commit
git commit -m "update and resolve conflict"
```
然后再push到你的仓库

**Comment by Yttehs-HDX** [comment]
> ```shell
> # 添加上游源
> git remote add upstream git@github.com:Vincent-ice/5th-loongson-class-in-NEUQ
> 
> # 拉取上游
> git fetch upstream
> git merge upstream/homework1
> 
> # 解决冲突
> mv week\ 1/作业提交/*.md ./作业提交/
> git rm week\ 1/ -r
> 
> # 提交 commit
> git commit -m "update and resolve conflict"
> ```
> 
> 然后再push到你的仓库

$ git fetch upstream
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Vincent-ice** [comment]
> > ```shell
> > # 添加上游源
> > git remote add upstream git@github.com:Vincent-ice/5th-loongson-class-in-NEUQ
> > 
> > # 拉取上游
> > git fetch upstream
> > git merge upstream/homework1
> > 
> > # 解决冲突
> > mv week\ 1/作业提交/*.md ./作业提交/
> > git rm week\ 1/ -r
> > 
> > # 提交 commit
> > git commit -m "update and resolve conflict"
> > ```
> > 
> > 然后再push到你的仓库
> 
> $ git fetch upstream
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

重新配置你的ssh key试试

**Comment by Yttehs-HDX** [comment]
> ```shell
> # 添加上游源
> git remote add upstream git@github.com:Vincent-ice/5th-loongson-class-in-NEUQ
> 
> # 拉取上游
> git fetch upstream
> git merge upstream/homework1
> 
> # 解决冲突
> mv week\ 1/作业提交/*.md ./作业提交/
> git rm week\ 1/ -r
> 
> # 提交 commit
> git commit -m "update and resolve conflict"
> ```
> 
> 然后再push到你的仓库

感谢同学

**Pull request merged**
